//Supports endpoints & ensures type safety
export enum SECURITY_LEVELS {
  UNCLASSIFIED = 0,
  CONFIDENTIAL = 1,
  SECRET = 2,
  TOP_SECRET = 3,
  PEER_TO_PEER = 4,
}

export enum ROLES {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  MEMBER = 'MEMBER',
}

export enum AUDIT_EVENTS {
  USER_CREATED_ORG_MEMBER = 'AUDIT_USER_CREATED_ORG_MEMBER',
  USER_UPDATED = 'AUDIT_USER_UPDATED',
  USER_REMOVED = 'AUDIT_USER_REMOVED',
  TEAM_CREATED = 'AUDIT_TEAM_CREATED',
  TEAM_UPDATED = 'AUDIT_TEAM_UPDATED',
  TEAM_DELETED = 'AUDIT_TEAM_DELETED',
  TEAM_MEMBER_ADDED = 'AUDIT_TEAM_MEMBER_ADDED',
  TEAM_MEMBER_REMOVED = 'AUDIT_TEAM_MEMBER_REMOVED',
  PROJECT_CREATED = 'AUDIT_PROJECT_CREATED',
  PROJECT_UPDATED = 'AUDIT_PROJECT_UPDATED',
  PROJECT_DELETED = 'AUDIT_PROJECT_DELETED',
  PROJECT_MEMBER_ADDED = 'AUDIT_PROJECT_MEMBER_ADDED',
  PROJECT_MEMBER_REMOVED = 'AUDIT_PROJECT_MEMBER_REMOVED',
  FILE_UPDATED = 'AUDIT_FILE_UPDATED',
  FILE_DELETED = 'AUDIT_FILE_DELETED',
  FILE_CLEARANCE_CHANGED = 'AUDIT_FILE_CLEARANCE_CHANGED',
  FILE_DOWNLOAD_INTENT = 'AUDIT_FILE_DOWNLOAD_INTENT',
  P2P_CREATED = 'AUDIT_P2P_CREATED',
  P2P_DELIVERED = 'AUDIT_P2P_DELIVERED',
  P2P_DELETED = 'AUDIT_P2P_DELETED',
  ACCESS_OVERRIDE_ADDED = 'AUDIT_ACCESS_OVERRIDE_ADDED',
  ACCESS_OVERRIDE_REMOVED = 'AUDIT_ACCESS_OVERRIDE_REMOVED',
  ACCESS_OVERRIDE_EXPIRED = 'AUDIT_ACCESS_OVERRIDE_EXPIRED',
}